"""PostgreSQL integration tests.

Requires ``MOCK_MES_TEST_DATABASE_URL`` pointing at a disposable database with
the mock-mes migration applied; skipped otherwise. Covers the Alembic
migration, idempotent per-day generation, batch-ledger hashing, window
boundaries (no future data), SQL row-level filtering and the "PG unavailable
is a loud error, never a memory fallback" behaviour.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from mock_mes.api.server import create_app
from mock_mes.config import MockMesSettings
from mock_mes.generator.engine import generate_day, is_workday, window_digest
from mock_mes.testing import (
    TEST_DATABASE_URL,
    TEST_WINDOW_END,
    TEST_WINDOW_START,
    connect_db,
    generate_test_window,
    reset_test_db,
    upgrade_test_db,
)
from pydantic import SecretStr

pytestmark = pytest.mark.skipif(
    TEST_DATABASE_URL is None,
    reason="set MOCK_MES_TEST_DATABASE_URL to a disposable database to run these tests",
)


@pytest_asyncio.fixture(scope="module")
async def migrated_db() -> str:
    url = str(TEST_DATABASE_URL)
    await upgrade_test_db(url)
    await reset_test_db(url)
    await generate_test_window(url)
    return url


async def _count(connection: Any, table: str) -> int:
    cursor = await connection.execute(f"SELECT COUNT(*) AS n FROM {table}")
    row = await cursor.fetchone()
    return int(row["n"])


@pytest.mark.asyncio
async def test_migration_creates_all_mock_tables(migrated_db: str) -> None:
    async with await connect_db(migrated_db) as connection:
        cursor = await connection.execute(
            "SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename"
        )
        tables = {str(row["tablename"]) for row in await cursor.fetchall()}
    expected = {
        "mock_dept",
        "mock_employee",
        "mock_huohao",
        "mock_sc_type",
        "mock_rfid_worktype",
        "mock_huohao_worktype",
        "mock_user_info",
        "mock_move_menu",
        "mock_dg",
        "mock_dg_zu",
        "mock_plan",
        "mock_sclzd",
        "mock_sclzd_worktype",
        "mock_barcode",
        "mock_barcode_cl",
        "mock_dg_cl",
        "mock_pin_feng",
        "mock_ysk",
        "mock_wsk",
        "mock_generate_batch",
        "alembic_version_mock_mes",
    }
    assert expected <= tables


@pytest.mark.asyncio
async def test_generation_is_idempotent_and_deterministic(migrated_db: str) -> None:
    async with await connect_db(migrated_db) as connection:
        before = {table: await _count(connection, table) for table in _BUSINESS_TABLES}
        settings = MockMesSettings()
        first = await generate_day(connection, settings, date(2026, 8, 10), "run-1")
        second = await generate_day(connection, settings, date(2026, 8, 10), "run-2")
        after = {table: await _count(connection, table) for table in _BUSINESS_TABLES}

    assert first.status == "skipped"  # already generated by the window fill
    assert second.status == "skipped"
    assert before == after  # nothing inserted twice (unique keys + batch ledger)


_BUSINESS_TABLES = (
    "mock_plan",
    "mock_sclzd",
    "mock_sclzd_worktype",
    "mock_barcode",
    "mock_barcode_cl",
    "mock_dg_cl",
    "mock_pin_feng",
    "mock_ysk",
    "mock_wsk",
)


@pytest.mark.asyncio
async def test_window_hash_is_reproducible(migrated_db: str) -> None:
    async with await connect_db(migrated_db) as connection:
        settings = MockMesSettings()
        first = await window_digest(connection, settings, TEST_WINDOW_START, TEST_WINDOW_END)
        second = await window_digest(connection, settings, TEST_WINDOW_START, TEST_WINDOW_END)
    assert first and first == second


@pytest.mark.asyncio
async def test_window_never_contains_future_days(migrated_db: str) -> None:
    async with await connect_db(migrated_db) as connection:
        cursor = await connection.execute("SELECT DISTINCT day FROM mock_generate_batch")
        days = {
            row["day"].date() if hasattr(row["day"], "date") else row["day"]
            for row in await cursor.fetchall()
        }
    assert days, "expected generated days"
    assert max(days) <= date(2026, 8, 21)  # virtual_now; never the real future


@pytest.mark.asyncio
async def test_batch_ledger_records_row_counts_and_hashes(migrated_db: str) -> None:
    async with await connect_db(migrated_db) as connection:
        cursor = await connection.execute(
            "SELECT day, scenario, seed, row_count, data_hash, status FROM mock_generate_batch "
            "ORDER BY day LIMIT 3"
        )
        rows = await cursor.fetchall()
    assert rows
    for row in rows:
        assert row["seed"] == MockMesSettings().seed
        assert row["status"] == "done"
        assert row["row_count"] >= 0
        assert len(row["data_hash"]) == 64


@pytest.mark.asyncio
async def test_invariants_hold_on_postgres_data(migrated_db: str) -> None:
    async with await connect_db(migrated_db) as connection:
        # je = sl × price across the three wage sources — checked in SQL so the
        # assertion stays fast at factory scale (hundreds of thousands of rows).
        cursor = await connection.execute(
            """
            SELECT
              (SELECT count(*) FROM mock_barcode_cl
                WHERE je <> sl * (payload->>'price')::numeric) AS bad_scan,
              (SELECT count(*) FROM mock_dg_cl
                WHERE je <> sl * (payload->>'price')::numeric) AS bad_hanging,
              (SELECT count(*) FROM mock_pin_feng
                WHERE je <> sl * (payload->>'price')::numeric) AS bad_manual,
              (SELECT count(*) FROM mock_barcode_cl) AS scan_rows
            """
        )
        tally = await cursor.fetchone()
        assert tally is not None
        assert tally["bad_scan"] == 0
        assert tally["bad_hanging"] == 0
        assert tally["bad_manual"] == 0
        assert tally["scan_rows"] > 0

        # Scanned worktypes are within the known worktype set.
        cursor = await connection.execute("SELECT DISTINCT worktype FROM mock_barcode")
        scanned = {str(row["worktype"]) for row in await cursor.fetchall()}
        assert scanned <= {"WT01", "WT02", "WT03"}

        # Wsk (unscanned) worktypes are part of the same set.
        cursor = await connection.execute("SELECT DISTINCT worktype FROM mock_wsk")
        unscanned = {str(row["worktype"]) for row in await cursor.fetchall()}
        assert unscanned <= {"WT01", "WT02", "WT03"}


@pytest.mark.asyncio
async def test_sql_row_level_filtering_visibility(migrated_db: str) -> None:
    """Company/role tiers are enforced in SQL: 99 whole, 02 bound depts, 01 own
    小组 (on personal uid rows), 00 own data only."""
    app = create_app(
        MockMesSettings(
            environment="test",
            database_url=SecretStr(migrated_db),
            virtual_now=datetime.fromisoformat("2026-08-21T08:00:00+00:00"),
            data_start=TEST_WINDOW_START,
            data_end=TEST_WINDOW_END,
        )
    )
    await app.state.db.open()
    try:
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as client:
            token = (await client.post("/api/system/token", json={"app_key": "APPKEY-A"})).json()[
                "result"
            ]
            params = {
                "app_key": token["appkey"],
                "timestamp": token["timestamp"],
                "sign": token["sign"],
                "page": 1,
                "size": 200,
                "Uid": "01001",
                "dates": "2026-07-01",
                "datee": "2026-08-31",
            }
            boss = (
                await client.post(
                    "/api/NetYf/Sclzd/YskQuery",
                    json=params,
                    headers={"Authorization": "Bearer MOCK-TOKEN-01009"},
                )
            ).json()["result"]["list"]
            manager = (
                await client.post(
                    "/api/NetYf/Sclzd/YskQuery",
                    json=params,
                    headers={"Authorization": "Bearer MOCK-TOKEN-01008"},
                )
            ).json()["result"]["list"]
            worker = (
                await client.post(
                    "/api/NetYf/Sclzd/YskQuery",
                    json=params,
                    headers={"Authorization": "Bearer MOCK-TOKEN-01001"},
                )
            ).json()["result"]["list"]
            # Leader scope is exercised without a Uid narrowing filter: the
            # group leader (01012, dept-a1 g02) must see only group members.
            leader_params = {k: v for k, v in params.items() if k != "Uid"}
            leader = (
                await client.post(
                    "/api/NetYf/Sclzd/YskQuery",
                    json=leader_params,
                    headers={"Authorization": "Bearer MOCK-TOKEN-01012"},
                )
            ).json()["result"]["list"]
    finally:
        await app.state.db.close()

    assert len(boss) >= len(manager) >= len(worker)
    assert all(row["dept"] == "dept-a1" for row in manager)
    assert all(row["uid"] == "01001" for row in worker)

    # 01 组长 sees only their bound 小组's member rows (SQL group_id subquery).
    async with await connect_db(migrated_db) as connection:
        cursor = await connection.execute(
            "SELECT group_id FROM mock_employee WHERE company = 'COMPANY-A' AND uid = '01012'"
        )
        row = await cursor.fetchone()
        group = str(row["group_id"]) if row else ""
        assert group
        cursor = await connection.execute(
            "SELECT uid FROM mock_employee WHERE company = 'COMPANY-A' AND group_id = %(g)s",
            {"g": group},
        )
        member_uids = {str(item["uid"]) for item in await cursor.fetchall()}
    assert leader
    leader_uids = {str(item["uid"]) for item in leader}
    assert leader_uids <= member_uids
    assert len(leader_uids) > 1


@pytest.mark.asyncio
async def test_pg_unavailable_is_a_loud_error_not_a_fallback() -> None:
    # Explicitly null the URL so the repository-root .env cannot satisfy it.
    with pytest.raises(RuntimeError):
        create_app(MockMesSettings(environment="test", database_url=None))
    # A bad connection must fail at startup, not silently fall back.
    app = create_app(
        MockMesSettings(
            environment="test",
            database_url=SecretStr("postgresql://mock_mes:wrong@127.0.0.1:1/mock_mes"),
            virtual_now=datetime.fromisoformat("2026-08-21T08:00:00+00:00"),
        )
    )
    with pytest.raises(Exception):
        await app.state.db.open()


@pytest.mark.asyncio
async def test_rolling_scans_only_land_on_workdays(migrated_db: str) -> None:
    """Rolling output never lands on weekends/holidays (work calendar)."""
    async with await connect_db(migrated_db) as connection:
        cursor = await connection.execute("SELECT DISTINCT rq FROM mock_barcode_cl")
        scan_days = [
            row["rq"].date() if hasattr(row["rq"], "date") else row["rq"]
            for row in await cursor.fetchall()
        ]
    for day in scan_days:
        assert is_workday(day), f"rolling scan landed on non-workday {day}"
