"""Protocols implemented by external adapters."""

from factory_agent.ports.cache import CacheStore
from factory_agent.ports.contracts import (
    ArtifactStore,
    AuthenticatedIdentity,
    Clock,
    IdentityProvider,
    MesDataSource,
    SessionRecord,
    SessionRepository,
    TrustedCredential,
)
from factory_agent.ports.model import (
    ModelErrorCategory,
    ModelGateway,
    ModelGatewayError,
    ModelMessage,
    ModelRequest,
    ModelResponse,
    ModelRole,
    ModelStage,
    ModelUsage,
)
from factory_agent.ports.session import (
    CapabilityRunner,
    CapabilityRunRequest,
    CapabilityRunResult,
    InteractionCommit,
    InteractionOwner,
    InteractionPage,
    InteractionStore,
    MessagePage,
    OutboxRecord,
    UsageEventSink,
    UsageOutbox,
    UsageOutboxEvent,
)

__all__ = [
    "ArtifactStore",
    "AuthenticatedIdentity",
    "CacheStore",
    "CapabilityRunRequest",
    "CapabilityRunResult",
    "CapabilityRunner",
    "Clock",
    "IdentityProvider",
    "InteractionCommit",
    "InteractionOwner",
    "InteractionPage",
    "InteractionStore",
    "MesDataSource",
    "MessagePage",
    "ModelErrorCategory",
    "ModelGateway",
    "ModelGatewayError",
    "ModelMessage",
    "ModelRequest",
    "ModelResponse",
    "ModelRole",
    "ModelStage",
    "ModelUsage",
    "OutboxRecord",
    "SessionRecord",
    "SessionRepository",
    "TrustedCredential",
    "UsageEventSink",
    "UsageOutbox",
    "UsageOutboxEvent",
]
