"""Protocols implemented by external adapters."""

from factory_agent.ports.cache import CacheStore
from factory_agent.ports.contracts import (
    ArtifactStore,
    AuthenticatedIdentity,
    Clock,
    CredentialBinder,
    CredentialExchange,
    IdentityProvider,
    MesDataSource,
    ResolvedPrincipal,
    SessionRecord,
    SessionRepository,
    TrustedCredential,
)
from factory_agent.ports.mes_progress import (
    MesFetchProgress,
    MesFetchProgressSink,
    publish_mes_fetch_progress,
    report_mes_fetch_progress,
)
from factory_agent.ports.model import (
    ModelDelta,
    ModelDeltaKind,
    ModelErrorCategory,
    ModelGateway,
    ModelGatewayError,
    ModelMessage,
    ModelRequest,
    ModelResponse,
    ModelRole,
    ModelStage,
    ModelStreamGateway,
    ModelUsage,
)
from factory_agent.ports.session import (
    CapabilityRunner,
    CapabilityRunRequest,
    CapabilityRunResult,
    ConversationCreation,
    ConversationPage,
    ConversationSummary,
    InteractionCommit,
    InteractionOwner,
    InteractionPage,
    InteractionStore,
    MesCallRecord,
    MesCallRecorder,
    MessagePage,
    UsageEvent,
)
from factory_agent.ports.tenant_registry import (
    TenantRegistryReader,
    TenantRegistryRecord,
)

__all__ = [
    "ArtifactStore",
    "AuthenticatedIdentity",
    "CacheStore",
    "CapabilityRunRequest",
    "CapabilityRunResult",
    "CapabilityRunner",
    "Clock",
    "ConversationCreation",
    "ConversationPage",
    "ConversationSummary",
    "CredentialBinder",
    "CredentialExchange",
    "IdentityProvider",
    "InteractionCommit",
    "InteractionOwner",
    "InteractionPage",
    "InteractionStore",
    "MesCallRecord",
    "MesCallRecorder",
    "MesDataSource",
    "MesFetchProgress",
    "MesFetchProgressSink",
    "MessagePage",
    "ModelDelta",
    "ModelDeltaKind",
    "ModelErrorCategory",
    "ModelGateway",
    "ModelGatewayError",
    "ModelMessage",
    "ModelRequest",
    "ModelResponse",
    "ModelRole",
    "ModelStage",
    "ModelStreamGateway",
    "ModelUsage",
    "ResolvedPrincipal",
    "SessionRecord",
    "SessionRepository",
    "TenantRegistryReader",
    "TenantRegistryRecord",
    "TrustedCredential",
    "UsageEvent",
    "publish_mes_fetch_progress",
    "report_mes_fetch_progress",
]
