apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: factory-agent
resources:
  - ../base
  - local-secrets.yaml
  - mock-mes.yaml
  - middleware.yaml
patches:
  - path: local-config.patch.yaml
